### PR TITLE
Update ExtraConfigurator.php

### PR DESCRIPTION
**Pull request by izytechAB**
Fix non working $_SERVER in parseEnvironmentParameters, changed to getenv()

### CODE REVIEW

**Comment by izytechAB** [comment]
This change is working in php v 7.3

**Comment by f3l1x** [comment]
Tests are failing. Why did you change it?

**Comment by izytechAB** [comment]
$_SERVER is not returning env variables if variables order does not conting "E". Since PHP 7.1 getenv() returns all env varibales regardless of variables order settings.

**Comment by f3l1x** [comment]
I will take a look, thanks.

**Comment by f3l1x** [comment]
After some time I think about it and I would like to stick with `$_SERVER`. Especially you can disable populating $_SERVER with skipping E in `variables_order` (https://www.php.net/manual/en/ini.core.php#ini.variables-order).

But thank you for your time.

**Pull request closed without merging**
