### PR TITLE
Allows to use different data source except $_SERVER

### PR DESCRIPTION
**Pull request by kedlas**
Created parseParameters method with signature offering to set variables source and prefix

### CODE REVIEW

**Comment by kedlas** [comment]
not needed anymore

**Comment by f3l1x** [comment]
I like that idea, could you please reopen it? :-)

**Comment by kedlas** [comment]
I can. But consider the getenv() condition. You're checking if passed data are present among env variables, so still you can't expect that every data you pass to that function will be handled and made a config from them.

**Comment by f3l1x** [comment]
Thanks.

**Pull request merged**
